{% set version = "0.7.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-piar
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/piar_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/piar/piar_{{ version }}.tar.gz
  sha256: 34355ac256e0a41294a85eb663e285893ff8a56b15851fb3d9a0de503deba212

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-matrix >=1.5_0
    - r-gpindex >=0.5.0
  run:
    - r-base
    - r-matrix >=1.5_0
    - r-gpindex >=0.5.0

test:
  commands:
    - $R -e "library('piar')"           # [not win]
    - "\"%R%\" -e \"library('piar')\""  # [win]

about:
  home: https://marberts.github.io/piar/, https://github.com/marberts/piar
  license: MIT
  summary: Most price indexes are made with a two-step procedure, where period-over-period elemental indexes are first calculated for a collection of elemental aggregates at each point in time, and then aggregated according to a price index aggregation structure. These indexes can then be chained together to form a time
    series that gives the evolution of prices with respect to a fixed base period. This package contains a collections of functions that revolve around this work flow, making it easy to build standard price indexes, and implement the methods described by Balk (2008, ISBN:978-1-107-40496-0), von der Lippe (2001, ISBN:3-8246-0638-0),
    and the CPI manual (2020, ISBN:978-1-51354-298-0) for bilateral price indexes.
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - marberts

# Package: piar
# Title: Price Index Aggregation
# Version: 0.6.0
# Authors@R: c( person("Steve", "Martin", role = c("aut", "cre", "cph"), email = "stevemartin041@gmail.com", comment = c(ORCID = "0000-0003-2544-9480")) )
# Description: Most price indexes are made with a two-step procedure, where period-over-period elemental indexes are first calculated for a collection of elemental aggregates at each point in time, and then aggregated according to a price index aggregation structure. These indexes can then be chained together to form a time series that gives the evolution of prices with respect to a fixed base period. This package contains a collections of functions that revolve around this work flow, making it easy to build standard price indexes, and implement the methods described by Balk (2008, ISBN:978-1-107-40496-0), von der Lippe (2001, ISBN:3-8246-0638-0), and the CPI manual (2020, ISBN:978-1-51354-298-0) for bilateral price indexes.
# Depends: R (>= 4.0)
# Imports: stats, utils, gpindex (>= 0.5.0), Matrix (>= 1.5-0)
# Suggests: rmarkdown, knitr, sps, testthat (>= 3.0.0)
# License: MIT + file LICENSE
# Encoding: UTF-8
# URL: https://marberts.github.io/piar/, https://github.com/marberts/piar
# BugReports: https://github.com/marberts/piar/issues
# LazyData: true
# VignetteBuilder: knitr
# Config/testthat/edition: 3
# RoxygenNote: 7.2.3
# NeedsCompilation: no
# Packaged: 2023-11-19 02:27:20 UTC; steve
# Author: Steve Martin [aut, cre, cph] (<https://orcid.org/0000-0003-2544-9480>)
# Maintainer: Steve Martin <stevemartin041@gmail.com>
# Repository: CRAN
# Date/Publication: 2023-11-19 03:10:02 UTC
